name: "Customize PR Title"
description: "Renames the PR Agent comment title"
inputs:
  token:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Customize PR Review Title
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const { owner, repo, number } = context.issue;

          const comments = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number: number,
          });

          const targetComment = comments.data.find(c =>
            c.body.includes('PR Reviewer Guide') &&
            c.user.type === 'Bot'
          );

          if (targetComment) {
            console.log(`Found PR Agent comment ID: ${targetComment.id}`);

            let newBody = targetComment.body;

            //Reviewer Guide başlığını değiştir
            newBody = newBody.replace(
              /## PR Reviewer Guide[^\n]*/g,
              '## 🎩 Review of Abralabs PR Agent'
            );

            //Code Suggestions başlığını değiştir
            newBody = newBody.replace(
              /## PR Code Suggestions[^\n]*/g,
              '## ✨ Suggestions of Abralabs PR Agent'
            );

            if (newBody !== targetComment.body) {
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: targetComment.id,
                body: newBody
              });
            } else {
              console.log('No matching headers found to update.');
            }
          }
