name: Auto Label PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm init -y
          npm install js-yaml @actions/github
          
      - name: Install label engine dependencies
        run: |
          cd .github/label-engine
          npm install @actions/core @actions/github   

      - name: Auto Label PR
        run: node .github/label-engine/index.cjs
        env:
          PROVIDER: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
